USE [master]
GO
/****** Object:  Database [TESTE]    Script Date: 17/05/2017 16:20:19 ******/
CREATE DATABASE [TESTE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TESTE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TESTE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TESTE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TESTE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TESTE] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TESTE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TESTE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TESTE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TESTE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TESTE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TESTE] SET ARITHABORT OFF 
GO
ALTER DATABASE [TESTE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TESTE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TESTE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TESTE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TESTE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TESTE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TESTE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TESTE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TESTE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TESTE] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TESTE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TESTE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TESTE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TESTE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TESTE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TESTE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TESTE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TESTE] SET RECOVERY FULL 
GO
ALTER DATABASE [TESTE] SET  MULTI_USER 
GO
ALTER DATABASE [TESTE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TESTE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TESTE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TESTE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TESTE] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TESTE', N'ON'
GO
USE [TESTE]
GO
/****** Object:  Table [dbo].[Produto]    Script Date: 17/05/2017 16:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Produto](
	[idproduto] [bigint] NOT NULL,
	[codigo] [varchar](20) NOT NULL,
	[descricao] [varchar](100) NULL,
	[preco] [float] NULL,
	[saldo] [float] NULL,
 CONSTRAINT [PK_idproduto] PRIMARY KEY CLUSTERED 
(
	[idproduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_codigo]    Script Date: 17/05/2017 16:20:19 ******/
CREATE NONCLUSTERED INDEX [IX_codigo] ON [dbo].[Produto]
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_descricao]    Script Date: 17/05/2017 16:20:19 ******/
CREATE NONCLUSTERED INDEX [IX_descricao] ON [dbo].[Produto]
(
	[descricao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TESTE] SET  READ_WRITE 
GO
